Feat: captainhook for commits hooks, phpstan, phpmd, php-cs-fixer and minor optimizations
heiseonline/shariff-backend-php pull request #194
Opened 2024-01-16 08:35 UTC by digitalgopnik

2024-05-16 19:21 UTC, liayn commented
What hinders merging this?

2026-05-28 11:34 UTC, trimethylpentan requested changes

2026-05-28 11:34 UTC, trimethylpentan commented on src/Backend.php
> +        $baseCacheKey = md5((string)json_encode($config));
```suggestion
        $baseCacheKey = md5((string)json_encode($config, JSON_THROW_ON_ERROR));
```

2026-05-28 11:51 UTC, digitalgopnik commented on src/Backend.php
> +        $baseCacheKey = md5((string)json_encode($config));
Fixed

2026-05-28 11:52 UTC, merged